-- ✈️ Airline Booking Analytics – SQL Case Study
-- Author: Arjun | Date: 2025-04-21

-- -----------------------------
-- 📘 Overview
-- -----------------------------

This case study focuses on analyzing flight bookings and passenger data to uncover trends in route popularity, seat class revenue, and high-value customers.

--

-- -----------------------------
-- 🗃️ Database Summary
-- -----------------------------

Database: `airline_bookings`

Tables:
- `passengers`: passenger_id, passenger_name, country
- `flights`: flight_id, origin, destination, flight_date
- `bookings`: booking_id, passenger_id, flight_id, seat_class, price

--

-- -----------------------------
-- ❓ Business Questions Answered
-- -----------------------------

1. What are the most booked flight routes?
2. How much revenue is generated by each seat class?
3. Who is the highest paying passenger?
4. Which flights have the most bookings?
5. How is revenue distributed by country?

--

-- -----------------------------
-- 📊 Sample SQL Queries
-- -----------------------------

-- ✅ Top Booked Routes
SELECT 
  f.origin, f.destination, COUNT(b.booking_id) AS total_bookings
FROM bookings b
JOIN flights f ON b.flight_id = f.flight_id
GROUP BY f.origin, f.destination
ORDER BY total_bookings DESC;

--

-- ✅ Revenue by Seat Class
SELECT 
  seat_class, SUM(price) AS total_revenue
FROM bookings
GROUP BY seat_class
ORDER BY total_revenue DESC;

--

-- ✅ Highest Paying Passenger
SELECT 
  p.passenger_name, SUM(b.price) AS total_spent
FROM bookings b
JOIN passengers p ON b.passenger_id = p.passenger_id
GROUP BY p.passenger_name
ORDER BY total_spent DESC
LIMIT 1;

--

-- -----------------------------
-- 💡 Key Insights
-- -----------------------------

- 🛫 Mumbai → Dubai was the most booked route
- 💼 Business class generated more revenue than Economy
- 👤 Arjun was the highest spending passenger
- 🌎 USA and UAE contributed significant revenue

--

-- -----------------------------
-- 📁 File Structure
-- -----------------------------

airline_bookings_case_study/
├── airline_bookings.sql     -- full SQL: schema, inserts, queries
└── README.md                -- this file
